// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3_g8W6l4IhtPrDBx9BQusyRXBYx7hZ9Q',
    appId: '1:875114470824:web:c142d317eddce4bad0119d',
    messagingSenderId: '875114470824',
    projectId: 'fury-chat-a5c19',
    authDomain: 'fury-chat-a5c19.firebaseapp.com',
    storageBucket: 'fury-chat-a5c19.firebasestorage.app',
    measurementId: 'G-0NQD00XT79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAPdV-fGqVTTh7LF64FTS0UWQ-xATtTUY',
    appId: '1:875114470824:android:a5535f3b1cbc7e23d0119d',
    messagingSenderId: '875114470824',
    projectId: 'fury-chat-a5c19',
    storageBucket: 'fury-chat-a5c19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvDhAvhCob_ts4FL1atqlKD1GIm5hRjJQ',
    appId: '1:875114470824:ios:97cd08a5b647ebd8d0119d',
    messagingSenderId: '875114470824',
    projectId: 'fury-chat-a5c19',
    storageBucket: 'fury-chat-a5c19.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvDhAvhCob_ts4FL1atqlKD1GIm5hRjJQ',
    appId: '1:875114470824:ios:97cd08a5b647ebd8d0119d',
    messagingSenderId: '875114470824',
    projectId: 'fury-chat-a5c19',
    storageBucket: 'fury-chat-a5c19.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3_g8W6l4IhtPrDBx9BQusyRXBYx7hZ9Q',
    appId: '1:875114470824:web:cce36a5a7ae4769fd0119d',
    messagingSenderId: '875114470824',
    projectId: 'fury-chat-a5c19',
    authDomain: 'fury-chat-a5c19.firebaseapp.com',
    storageBucket: 'fury-chat-a5c19.firebasestorage.app',
    measurementId: 'G-R8TF6R7JL9',
  );
}
